# report bandwidth iops latency

[global]
ioengine=posixaio
iodepth=4
blocksize=4m
filename_format=$jobname/00/$filenum

[8g-detector-write-split]
description='detector write, separate workloads'
filesize=8g
nrfiles=5000
startdelay=1s-5m
group_reporting=1
ramp_time=5
rw=write
openfiles=1
loops=2

[8g-detector-prelayout]
description='detector read, separate workloads, w/ prelayout'
filesize=8g
nrfiles=5000
startdelay=1s-5m
numjobs=4
group_reporting=1
ramp_time=5
rw=read
openfiles=10
loops=2
