# report bandwidth iops latency

[global]
ioengine=posixaio
iodepth=4
blocksize=1m
filename_format=$jobname/00/$filenum

[1m-detector-write-split]
description='detector write, separate workloads'
filesize=1m
nrfiles=5000
startdelay=1s-5m
group_reporting=1
ramp_time=5
rw=write
openfiles=1
loops=30

[1m-detector-prelayout]
description='detector read, separate workloads, w/ prelayout'
filesize=1m
nrfiles=5000
startdelay=1s-5m
numjobs=4
group_reporting=1
ramp_time=5
rw=read
openfiles=10
loops=60
